workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - test

.before_script_template:
  before_script:
    - source /home/ubuntu/miniconda3/etc/profile.d/conda.sh
    - conda activate /home/ubuntu/.conda/envs/54gene-wgs-germline

test_integration1:
  extends: .before_script_template
  stage: test
  script:
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/fastqc_only_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh
  tags:
    - shell

test_integration2:
  extends: .before_script_template
  stage: test
  script:
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/joint_geno_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh
  tags:
    - shell

test_integration3:
  extends: .before_script_template
  stage: test
  script:
    - echo "FULL_JOB_ID=$CI_JOB_ID" >> full.env
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/full_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh
  artifacts:
    reports:
      dotenv: full.env
  tags:
    - shell

unit_tests:
  extends: .before_script_template
  stage: test
  script:
    - coverage run -m pytest workflow/scripts/tests/test*.py
    - coverage report | tee coverage.txt
  artifacts:
    paths:
      - coverage.txt
  coverage: '/TOTAL.*\s+(\d+\%)/'
  tags:
    - shell

functional_unit_test3:
  extends: .before_script_template
  stage: test
  script:
    - echo "$FULL_JOB_ID"
    - snakemake_unit_tests.out -c /54gene-gds/gitlab_runner/54gene-wgs-test-data/config.full_run.yaml
    - pytest /home/gitlab-runner/builds/dq_f2xRs/"${FULL_JOB}"/data-analysis5/dna-sequencing/54gene-wgs-germline/tests/unit/test_*py
  tags:
    - shell
