image: cpalmer718/snakemake-gcc

stages:
  - pytest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

run_all:
  stage: pytest
  script:
    - python -m pytest workflow/scripts/tests/
