workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - test

.before_script_template:
  before_script:
    - source /home/ubuntu/miniconda3/etc/profile.d/conda.sh
    - conda activate /home/ubuntu/.conda/envs/54gene-wgs-germline
  tags:
    - shell

test_integration1:
  extends: .before_script_template
  stage: test
  script:
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/fastqc_only_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh


test_integration2:
  extends: .before_script_template
  stage: test
  script:
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/joint_geno_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh


test_integration3:
  extends: .before_script_template
  stage: test
  script:
    - echo "$CI_CONCURRENT_ID"
    - "JOB_ID=$(echo $CI_CONCURRENT_ID)"
    - echo "FULL_JOB_ID=$JOB_ID" >> full.env
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/full_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh
  artifacts:
    reports:
      dotenv: full.env
  cache:
    key: full-run-cache
    untracked: true 
    paths:
      - $CI_PROJECT_DIR/*

unit_tests:
  extends: .before_script_template
  stage: test
  script:
    - coverage run -m pytest workflow/scripts/tests/test*.py
    - coverage report | tee coverage.txt
  artifacts:
    paths:
      - coverage.txt
  coverage: '/TOTAL.*\s+(\d+\%)/'

functional_unit_test3:
  extends: .before_script_template
  stage: test
  script:
    - echo "$FULL_JOB_ID"
    - cp /54gene-gds/gitlab_runner/snakemake_unit_tests/config.full_run.yaml .
    - snakemake_unit_tests.out -c config.full_run.yaml -o /home/ubuntu/builds/tests/full_mode/54gene-wgs-germline/tests -s ${CI_BUILDS_DIR}/${CI_RUNNER_SHORT_TOKEN}/"${FULL_JOB_ID}"/${CI_PROJECT_PATH}/workflow/Snakefile -p ${CI_BUILDS_DIR}/${CI_RUNNER_SHORT_TOKEN}/"${FULL_JOB_ID}"/${CI_PROJECT_PATH} -l ${CI_BUILDS_DIR}/${CI_RUNNER_SHORT_TOKEN}/"${FULL_JOB_ID}"/${CI_PROJECT_PATH}/WGS_log.out --update-all
    - pytest ${CI_BUILDS_DIR}/${CI_RUNNER_SHORT_TOKEN}/"${FULL_JOB_ID}"/${CI_PROJECT_PATH}/tests/unit/test*.py
  needs:
    - job: test_integration3
      artifacts: true
  cache:
    key: full-run-cache

