workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
   - build
   - test

run_fastqc:
  stage: build
  before_script:
    - source /home/ubuntu/miniconda3/etc/profile.d/conda.sh
    - conda activate /home/ubuntu/.conda/envs/54gene-wgs-germline
  script:
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/fastqc_only_mode/config/* config/
    - cp /54gene-gds/gitlab_runner/54gene-wgs-test-data/run_local_test.sh .
    - cp -r /54gene-gds/gitlab_runner/54gene-wgs-test-data/resources .
    - bash run_local_test.sh
  tags:
    - shell

run_pytest:
  stage: test
  image: cpalmer718/snakemake-gcc
  script:
    - python -m pytest workflow/scripts/tests/
  tags:
    - docker
