$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  sampleFile:
    type: string
  intervalsFile:
    type: string
  sexLinker:
    type: string
  jobs:
    type: integer
    minimum: 1
  tempDir:
    type: string
  runType:
    type: object
    properties:
      full:
        type: boolean
      joint_genotyping:
        type: boolean
      fastq_qc_only:
        type: boolean
    required:
      - full
      - joint_genotyping
      - fastq_qc_only
    additionalProperties: false
  global_vars:
    type: string
  cluster_mode:
    type: string
  default_queue:
    type: string
  compute_queue:
    type: string
  memory_queue:
    type: string
  bed:
    type: string
  max_concurrent:
    type: integer
    minimum: 1
  max_het_ratio:
    type: number
    exclusiveMinimum: 0
  min_avg_depth:
    type: number
    exclusiveMinimum: 0
  max_contam:
    type: number
    minimum: 0
    maximum: 1
  somalier:
    type: boolean
  fastqc:
    type: object
    properties:
      threads:
        type: number
        minimum: 1
      memory:
        type: number
        minimum: 100
    required:
      - threads
      - memory
    additionalProperties: false
  fastp:
    type: object
    properties:
      threads:
        type: number
        minimum: 1
      memory:
        type: number
        minimum: 100
    required:
      - threads
      - memory
    additionalProperties: false
  bwa:
    type: object
    properties:
      threads:
        type: number
        minimum: 1
      memory:
        type: number
        minimum: 100
    required:
      - threads
      - memory
    additionalProperties: false
  samtools_sort:
    type: object
    properties:
      threads:
        type: number
        minimum: 1
      memory:
        type: number
        minimum: 100
    required:
      - threads
      - memory
    additionalProperties: false
  markDuplicates:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  baseRecalibrator:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  applyBQSR:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  haplotypeCaller:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  gatherVcfs:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  genomicsDBImport:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
      batch_size:
        type: integer
        minimum: 1
      reader_threads:
        type: integer
        minimum: 1
    required:
      - memory
      - xmx
      - java_opts
      - batch_size
      - reader_threads
    additionalProperties: false
  genotypeGVCFs:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      max_alt_alleles:
        type: integer
        minimum: 1
      genomicsdb_max_alt_alleles:
        type: integer
        minimum: 1
      max_genotype_count:
        type: integer
        minimum: 2
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - max_alt_alleles
      - genomicsdb_max_alt_alleles
      - max_genotype_count
      - java_opts
    additionalProperties: false
  bcftools:
    type: object
    properties:
      memory:
        type: number
        minimum: 1
      threads:
        type: integer
        minimum: 1
    required:
      - memory
      - threads
    additionalProperties: false
  selectVariants:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  variantFiltration:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      xmx:
        type: number
        minimum: 100
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
  verifyBamID:
    type: object
    properties:
      memory:
        type: number
        minimum: 100
      region:
        type: array
        items:
          type: string
          pattern: "^chr[1-9]$|^chr1[0-9]$|^chr2[0-2]$|^chr[XYM]$"
    required:
      - memory
      - region
    additionalProperties: false
  picardCollectVariantCallingMetrics:
    type: object
    properties:
      memory:
        type: number
      xmx:
        type: number
      java_opts:
        type: ["string", "null"]
    required:
      - memory
      - xmx
      - java_opts
    additionalProperties: false
# entries that have to be in the config file for successful validation
required:
  - sampleFile
  - sexLinker
  - intervalsFile
  - jobs
  - tempDir
  - runType
  - global_vars
  - cluster_mode
  - default_queue
  - compute_queue
  - memory_queue
  - bed
  - max_concurrent
  - max_het_ratio
  - min_avg_depth
  - max_contam
  - somalier
  - fastqc
  - fastp
  - bwa
  - samtools_sort
  - markDuplicates
  - baseRecalibrator
  - applyBQSR
  - haplotypeCaller
  - gatherVcfs
  - genomicsDBImport
  - genotypeGVCFs
  - bcftools
  - selectVariants
  - variantFiltration
  - verifyBamID
  - picardCollectVariantCallingMetrics
additionalProperties: false
